import { Outfit } from 'next/font/google';
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import {AuthProviderContext} from '../app/context/context';
import Header from './components/Header';
import Footer from './components/Footer';

const outfit = Outfit({
    subsets: ['latin'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${outfit.className} antialiased`}>
                    <AuthProviderContext>
                        <Header />
                        {children}
                        <Footer />
                    </AuthProviderContext>
                </body>
            </html>
        </ClerkProvider>
    );
}
